import {
  ConfigPlugin,
  withAppBuildGradle,
  withProjectBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
} from "expo/config-plugins";
import fs from "fs";
import path from "path";

// Injects the Jetpack Glance loadpoint widget into the prebuilt Android
// project. Android counterpart of the @bacons/apple-targets iOS widget.
//
// ⚠ The Glance/Compose gradle wiring below is the #1 thing to verify after
// `expo prebuild`: the Compose compiler must match the project's Kotlin
// version. See targets/android-widget/README.md.

const PACKAGE = "io.evcc.android";
const WIDGET_SUBDIR = "widget"; // io.evcc.android.widget
const KOTLIN_SRC = "targets/android-widget/kotlin";
// generated by `npm run widget:strings` (scripts/build-widget-strings.mts) - a
// values/ + values-b+<locale>/ tree of strings.xml, copied into res/ verbatim.
const STRINGS_RES_SRC = "targets/android-widget/res";

const GLANCE_VERSION = "1.1.1";
// Compose compiler is versioned with Kotlin (2.0+). Must match the project's
// Kotlin version — check `android/build.gradle` after prebuild if it changes.
const COMPOSE_KOTLIN = "2.1.20";

// Root build.gradle: put the Compose compiler gradle plugin on the buildscript
// classpath so app/build.gradle can `apply plugin`. Without this the build
// fails with "Plugin with id 'org.jetbrains.kotlin.plugin.compose' not found".
const withComposeClasspath: ConfigPlugin = (config) =>
  withProjectBuildGradle(config, (config) => {
    if (!config.modResults.contents.includes("compose-compiler-gradle-plugin")) {
      const cp = `classpath("org.jetbrains.kotlin:compose-compiler-gradle-plugin:${COMPOSE_KOTLIN}")`;
      config.modResults.contents = config.modResults.contents.replace(
        /(classpath\(["']com\.android\.tools\.build:gradle["'][^\n]*\)\n)/,
        (m) => `${m}        ${cp}\n`,
      );
    }
    return config;
  });

const withGlanceGradle: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (config) => {
    let src = config.modResults.contents;

    if (!src.includes("glance-appwidget")) {
      // Glance brings a compatible Compose runtime transitively, so no BOM needed.
      const deps = [
        `    implementation("androidx.glance:glance-appwidget:${GLANCE_VERSION}")`,
        `    implementation("androidx.glance:glance-material3:${GLANCE_VERSION}")`,
      ].join("\n");
      src = src.replace(/dependencies\s*\{/, (m) => `${m}\n${deps}`);
    }

    // enable Compose for the app module (needed to compile Glance @Composable)
    if (!src.includes("buildFeatures") || !/compose\s+true/.test(src)) {
      src = src.replace(
        /android\s*\{/,
        (m) => `${m}\n    buildFeatures {\n        compose true\n    }`,
      );
    }

    config.modResults.contents = src;
    return config;
  });

const withGlanceComposeCompiler: ConfigPlugin = (config) =>
  // Kotlin 2.0+: the Compose compiler is a gradle plugin. Apply it to the app
  // module. (For Kotlin < 2.0 use composeOptions.kotlinCompilerExtensionVersion
  // instead — see README.)
  withAppBuildGradle(config, (config) => {
    const apply = `apply plugin: "org.jetbrains.kotlin.plugin.compose"`;
    if (!config.modResults.contents.includes(apply)) {
      config.modResults.contents = `${apply}\n${config.modResults.contents}`;
    }
    return config;
  });

// The manifest types don't model android:label or <meta-data> on <receiver>
// (Expo's typings only add them for activities/applications), though the
// manifest XML writer accepts both fine.
type ManifestReceiver = NonNullable<AndroidConfig.Manifest.ManifestApplication["receiver"]>[number];
type LabeledManifestReceiver = ManifestReceiver & {
  $: ManifestReceiver["$"] & { "android:label"?: string };
  "meta-data"?: AndroidConfig.Manifest.ManifestMetaData[];
};

const pushWidgetReceiver = (
  app: AndroidConfig.Manifest.ManifestApplication,
  shortName: string,
  infoResource: string,
  label: string,
) => {
  app.receiver = app.receiver ?? [];
  const name = `.${WIDGET_SUBDIR}.${shortName}`;
  if (app.receiver.some((r) => r.$["android:name"] === name)) return;
  const receiver: LabeledManifestReceiver = {
    $: { "android:name": name, "android:exported": "false", "android:label": label },
    "intent-filter": [
      { action: [{ $: { "android:name": "android.appwidget.action.APPWIDGET_UPDATE" } }] },
    ],
    "meta-data": [
      {
        $: {
          "android:name": "android.appwidget.provider",
          "android:resource": `@xml/${infoResource}`,
        },
      },
    ],
  };
  app.receiver.push(receiver);
};

const withWidgetReceiver: ConfigPlugin = (config) =>
  withAndroidManifest(config, (config) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);

    pushWidgetReceiver(app, "EvccLoadpointWidgetReceiver", "loadpoint_widget_info", "Loadpoint");

    // widget placement configuration Activity (server, then loadpoint picker)
    app.activity = app.activity ?? [];
    const actName = `.${WIDGET_SUBDIR}.LoadpointWidgetConfigActivity`;
    if (!app.activity.some((a) => a.$["android:name"] === actName)) {
      app.activity.push({
        $: { "android:name": actName, "android:exported": "true" },
        "intent-filter": [
          {
            action: [{ $: { "android:name": "android.appwidget.action.APPWIDGET_CONFIGURE" } }],
          },
        ],
      });
    }
    return config;
  });

// Resize bounds pinned to LoadpointWidget.kt's two SizeMode.Responsive
// breakpoints (SMALL_SIZE 180x110 / WIDE_SIZE 340x110dp) - height is fixed
// since only width varies between them. Letting the launcher grant an
// intermediate/taller size than either breakpoint leaves the Glance content
// (sized for whichever breakpoint LocalSize resolves to) stranded inside a
// bigger real container than it was laid out for.
const widgetInfoXml = (pkg: string) => `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="180dp"
    android:minHeight="110dp"
    android:minResizeWidth="180dp"
    android:minResizeHeight="110dp"
    android:maxResizeWidth="340dp"
    android:maxResizeHeight="110dp"
    android:targetCellWidth="3"
    android:targetCellHeight="2"
    android:updatePeriodMillis="1800000"
    android:resizeMode="horizontal"
    android:widgetCategory="home_screen"
    android:configure="${pkg}.${WIDGET_SUBDIR}.LoadpointWidgetConfigActivity"
    android:previewImage="@drawable/widget_preview_loadpoint"
    android:previewLayout="@layout/loadpoint_widget_preview" />
`;

// Reload button icon (LoadpointWidget.kt only, mirrors iOS's "arrow.clockwise"
// SF Symbol next to the title). Standard Material "refresh" glyph, tinted at
// runtime via Glance's ColorFilter.tint() so it follows day/night like the
// rest of the widget's text.
const reloadIconVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="24" android:viewportHeight="24">
    <path android:fillColor="#FF000000"
        android:pathData="M17.65,6.35C16.2,4.9 14.21,4 12,4c-4.42,0 -7.99,3.58 -7.99,8s3.57,8 7.99,8c3.73,0 6.84,-2.55 7.73,-6h-2.08c-0.82,2.33 -3.04,4 -5.65,4 -3.31,0 -6,-2.69 -6,-6s2.69,-6 6,-6c1.66,0 3.14,0.69 4.22,1.78L13,11h7V4l-2.35,2.35z" />
</vector>
`;

// Loadpoint preview image: a card with title / status / power lines and a row
// of mode "pills" (one highlighted), so it reads as a loadpoint, not a chart.
const loadpointPreviewImageVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="250dp" android:height="140dp"
    android:viewportWidth="250" android:viewportHeight="140">
    <path android:fillColor="#1B1B1B" android:pathData="M0,0h250v140h-250z" />
    <path android:fillColor="#FFFFFF" android:pathData="M16,18h84v12h-84z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M16,38h120v9h-120z" />
    <path android:fillColor="#FFFFFF" android:pathData="M16,56h70v20h-70z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M16,104h34v16h-34z" />
    <path android:fillColor="#0FDE41" android:pathData="M56,104h34v16h-34z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M96,104h34v16h-34z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M136,104h34v16h-34z" />
</vector>
`;

// Static preview layout shown in the widget picker (the Glance content only
// renders once placed). Kept representative of the real widget.
const loadpointPreviewXml = `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#1B1B1B"
    android:padding="12dp">
    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:text="Loadpoint" android:textColor="#FFFFFF" android:textSize="14sp" android:textStyle="bold" />
    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:text="Charging · 62%" android:textColor="#B3FFFFFF" android:textSize="12sp" android:paddingTop="2dp" />
    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:text="7.4 kW" android:textColor="#FFFFFF" android:textSize="20sp" android:paddingTop="2dp" />
    <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content"
        android:orientation="horizontal" android:paddingTop="8dp">
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="off" android:textColor="#B3FFFFFF" android:textSize="12sp" android:paddingEnd="10dp" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="pv" android:textColor="#0FDE41" android:textSize="12sp" android:paddingEnd="10dp" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="min+pv" android:textColor="#B3FFFFFF" android:textSize="12sp" android:paddingEnd="10dp" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="now" android:textColor="#B3FFFFFF" android:textSize="12sp" />
    </LinearLayout>
</LinearLayout>
`;

const withWidgetFiles: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const root = config.modRequest.platformProjectRoot; // android/
      const main = path.join(root, "app", "src", "main");

      // derive the package from config so a fork test build can use a distinct
      // applicationId (e.g. io.evcc.android.dev) and coexist with the official app.
      const pkg = config.android?.package ?? PACKAGE;

      // 1. Kotlin sources → java/<pkg>/widget/, rewriting every occurrence of the
      // placeholder package (not just the `package` line, since files also
      // `import io.evcc.android.R` for string resources) to the app's actual
      // package - so a fork test build (io.evcc.android.dev) works too.
      const dest = path.join(main, "java", ...pkg.split("."), WIDGET_SUBDIR);
      fs.mkdirSync(dest, { recursive: true });
      const srcDir = path.join(config.modRequest.projectRoot, KOTLIN_SRC);
      const packageRe = new RegExp(PACKAGE.replace(/\./g, "\\."), "g");
      for (const f of fs.readdirSync(srcDir).filter((f) => f.endsWith(".kt"))) {
        const src = fs.readFileSync(path.join(srcDir, f), "utf8").replace(packageRe, pkg);
        fs.writeFileSync(path.join(dest, f), src);
      }

      // 2. res/xml widget info + a minimal preview layout
      const xmlDir = path.join(main, "res", "xml");
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, "loadpoint_widget_info.xml"), widgetInfoXml(pkg));

      const layoutDir = path.join(main, "res", "layout");
      fs.mkdirSync(layoutDir, { recursive: true });
      fs.writeFileSync(path.join(layoutDir, "loadpoint_widget_preview.xml"), loadpointPreviewXml);

      const drawableDir = path.join(main, "res", "drawable");
      fs.mkdirSync(drawableDir, { recursive: true });
      fs.writeFileSync(path.join(drawableDir, "widget_preview_loadpoint.xml"), loadpointPreviewImageVector);
      fs.writeFileSync(path.join(drawableDir, "ic_reload.xml"), reloadIconVector);

      // 3. localized strings.xml per locale (generated by `npm run widget:strings`).
      // The default values/strings.xml already exists (app_name etc. from the
      // Expo prebuild) - merge our <string> entries into it rather than
      // overwriting; the locale-qualified dirs don't exist yet, so those are a
      // plain copy.
      const stringsResDir = path.join(config.modRequest.projectRoot, STRINGS_RES_SRC);
      if (fs.existsSync(stringsResDir)) {
        for (const localeDir of fs.readdirSync(stringsResDir)) {
          const destDir = path.join(main, "res", localeDir);
          fs.mkdirSync(destDir, { recursive: true });
          const destFile = path.join(destDir, "strings.xml");
          const widgetXml = fs.readFileSync(path.join(stringsResDir, localeDir, "strings.xml"), "utf8");

          if (fs.existsSync(destFile)) {
            const widgetEntries = widgetXml.match(/^\s*<string\b[\s\S]*?<\/string>\s*$/gm)?.join("\n") ?? "";
            const existing = fs.readFileSync(destFile, "utf8");
            fs.writeFileSync(destFile, existing.replace("</resources>", `${widgetEntries}\n</resources>`));
          } else {
            fs.writeFileSync(destFile, widgetXml);
          }
        }
      }

      return config;
    },
  ]);

const withAndroidWidget: ConfigPlugin = (config) => {
  config = withComposeClasspath(config);
  config = withGlanceGradle(config);
  config = withGlanceComposeCompiler(config);
  config = withWidgetReceiver(config);
  config = withWidgetFiles(config);
  return config;
};

export default withAndroidWidget;
