import {
  ConfigPlugin,
  withAppBuildGradle,
  withProjectBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
} from "expo/config-plugins";
import fs from "fs";
import path from "path";

// Injects the Jetpack Glance loadpoint widget into the prebuilt Android
// project. Android counterpart of the @bacons/apple-targets iOS widget.

const PACKAGE = "io.evcc.android";
const WIDGET_SUBDIR = "widget"; // io.evcc.android.widget
const KOTLIN_SRC = "targets/android-widget/kotlin";
// Translations: shared widget strings come from the committed iOS string
// catalog (generated by `npm run widget:strings`), Android-only config
// Activity strings straight from this app's i18n JSON.
const XCSTRINGS = "targets/widget/Localizable.xcstrings";
const APP_I18N = "i18n";
const ANDROID_ONLY_PREFIX = "widget.androidConfig.";

const GLANCE_VERSION = "1.1.1";

// The Compose compiler gradle plugin is versioned with Kotlin (2.0+) and must
// match the Kotlin version React Native's gradle plugin pins.
function kotlinVersion(projectRoot: string): string {
  const toml = fs.readFileSync(
    path.join(
      projectRoot,
      "node_modules/react-native/gradle/libs.versions.toml",
    ),
    "utf8",
  );
  const m = toml.match(/^kotlin\s*=\s*"([^"]+)"/m);
  if (!m)
    throw new Error(
      "withAndroidWidget: Kotlin version not found in react-native libs.versions.toml",
    );
  return m[1];
}

const withComposeClasspath: ConfigPlugin = (config) =>
  withProjectBuildGradle(config, (config) => {
    if (
      !config.modResults.contents.includes("compose-compiler-gradle-plugin")
    ) {
      const cp = `classpath("org.jetbrains.kotlin:compose-compiler-gradle-plugin:${kotlinVersion(config.modRequest.projectRoot)}")`;
      config.modResults.contents = config.modResults.contents.replace(
        /(classpath\(["']com\.android\.tools\.build:gradle["'][^\n]*\)\n)/,
        (m) => `${m}    ${cp}\n`,
      );
    }
    return config;
  });

const withGlanceGradle: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (config) => {
    let src = config.modResults.contents;

    const apply = `apply plugin: "org.jetbrains.kotlin.plugin.compose"`;
    if (!src.includes(apply)) src = `${apply}\n${src}`;

    if (!src.includes("glance-appwidget")) {
      // Glance brings a compatible Compose runtime transitively, so no BOM needed.
      const deps = [
        `    implementation("androidx.glance:glance-appwidget:${GLANCE_VERSION}")`,
        `    implementation("androidx.glance:glance-material3:${GLANCE_VERSION}")`,
      ].join("\n");
      src = src.replace(/dependencies\s*\{/, (m) => `${m}\n${deps}`);
    }

    if (!/compose\s+true/.test(src)) {
      src = src.replace(
        /android\s*\{/,
        (m) => `${m}\n    buildFeatures {\n        compose true\n    }`,
      );
    }

    config.modResults.contents = src;
    return config;
  });

// Expo's manifest types don't model android:label or <meta-data> on
// <receiver>, though the XML writer accepts both.
type ManifestReceiver = NonNullable<
  AndroidConfig.Manifest.ManifestApplication["receiver"]
>[number];
type LabeledManifestReceiver = ManifestReceiver & {
  $: ManifestReceiver["$"] & { "android:label"?: string };
  "meta-data"?: AndroidConfig.Manifest.ManifestMetaData[];
};

// The forecast widgets (Solar/Price/CO₂/Feed-in) share one appwidget-provider
// XML, but each gets a distinct android:label so the widget picker names them.
const FORECAST_RECEIVERS = [
  { name: "EvccSolarWidgetReceiver", label: "@string/widget_name_solar" },
  { name: "EvccPriceWidgetReceiver", label: "@string/widget_name_price" },
  { name: "EvccCo2WidgetReceiver", label: "@string/widget_name_co2" },
  { name: "EvccFeedinWidgetReceiver", label: "@string/widget_name_feedin" },
];

const pushWidgetReceiver = (
  app: AndroidConfig.Manifest.ManifestApplication,
  shortName: string,
  infoResource: string,
  label: string,
) => {
  app.receiver = app.receiver ?? [];
  const name = `.${WIDGET_SUBDIR}.${shortName}`;
  if (app.receiver.some((r) => r.$["android:name"] === name)) return;
  const receiver: LabeledManifestReceiver = {
    $: { "android:name": name, "android:exported": "false", "android:label": label },
    "intent-filter": [
      {
        action: [
          {
            $: {
              "android:name": "android.appwidget.action.APPWIDGET_UPDATE",
            },
          },
        ],
      },
    ],
    "meta-data": [
      {
        $: {
          "android:name": "android.appwidget.provider",
          "android:resource": `@xml/${infoResource}`,
        },
      },
    ],
  };
  app.receiver.push(receiver);
};

const withWidgetManifest: ConfigPlugin = (config) =>
  withAndroidManifest(config, (config) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(
      config.modResults,
    );

    pushWidgetReceiver(
      app,
      "EvccLoadpointWidgetReceiver",
      "loadpoint_widget_info",
      "@string/widget_loadpoint_name",
    );
    for (const r of FORECAST_RECEIVERS) {
      pushWidgetReceiver(app, r.name, "forecast_widget_info", r.label);
    }

    // widget placement configuration Activities (loadpoint picker; forecast
    // server + adjust-toggle picker)
    app.activity = app.activity ?? [];
    for (const activityName of [
      `.${WIDGET_SUBDIR}.LoadpointWidgetConfigActivity`,
      `.${WIDGET_SUBDIR}.ForecastWidgetConfigActivity`,
    ]) {
      if (app.activity.some((a) => a.$["android:name"] === activityName)) {
        continue;
      }
      app.activity.push({
        $: { "android:name": activityName, "android:exported": "true" },
        "intent-filter": [
          {
            action: [
              {
                $: {
                  "android:name":
                    "android.appwidget.action.APPWIDGET_CONFIGURE",
                },
              },
            ],
          },
        ],
      });
    }
    return config;
  });

// Always one cell high; 4x1 (mode selector docked) by default, horizontally
// shrinkable down to 1x1. LoadpointWidget.kt switches layout by width.
const widgetInfoXml = `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="250dp"
    android:minHeight="40dp"
    android:minResizeWidth="40dp"
    android:minResizeHeight="40dp"
    android:targetCellWidth="4"
    android:targetCellHeight="1"
    android:updatePeriodMillis="1800000"
    android:resizeMode="horizontal"
    android:widgetCategory="home_screen"
    android:widgetFeatures="reconfigurable"
    android:configure="${PACKAGE}.${WIDGET_SUBDIR}.LoadpointWidgetConfigActivity"
    android:previewImage="@drawable/widget_preview_loadpoint"
    android:previewLayout="@layout/loadpoint_widget_preview" />
`;

// Forecast widgets have one fixed size (no size-variant layout like Loadpoint's
// responsive breakpoints) - no resizeMode, so the launcher can't grow the frame
// past ForecastWidget.kt's content and leave blank space below the footer.
const forecastInfoXml = `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="250dp"
    android:minHeight="110dp"
    android:targetCellWidth="4"
    android:targetCellHeight="2"
    android:updatePeriodMillis="1800000"
    android:widgetCategory="home_screen"
    android:configure="${PACKAGE}.${WIDGET_SUBDIR}.ForecastWidgetConfigActivity"
    android:previewImage="@drawable/widget_preview_forecast"
    android:previewLayout="@layout/forecast_widget_preview" />
`;

// Material "refresh" glyph, tinted at runtime via Glance's ColorFilter.tint().
const reloadIconVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="24" android:viewportHeight="24">
    <path android:fillColor="#FF000000"
        android:pathData="M17.65,6.35C16.2,4.9 14.21,4 12,4c-4.42,0 -7.99,3.58 -7.99,8s3.57,8 7.99,8c3.73,0 6.84,-2.55 7.73,-6h-2.08c-0.82,2.33 -3.04,4 -5.65,4 -3.31,0 -6,-2.69 -6,-6s2.69,-6 6,-6c1.66,0 3.14,0.69 4.22,1.78L13,11h7V4l-2.35,2.35z" />
</vector>
`;

// Widget picker preview image (4x1): name / status, SoC, power, docked mode buttons, bottom progress strip.
const loadpointPreviewImageVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="300dp" android:height="70dp"
    android:viewportWidth="300" android:viewportHeight="70">
    <path android:fillColor="#1B1B1B" android:pathData="M0,0h300v70h-300z" />
    <path android:fillColor="#FFFFFF" android:pathData="M12,18h40v30h-40z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M56,38h12v9h-12z" />
    <path android:fillColor="#FFFFFF" android:pathData="M80,20h70v10h-70z" />
    <path android:fillColor="#0FDE41" android:pathData="M80,36h64v7h-64z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M180,10h12v12h-12z" />
    <path android:fillColor="#2C2C2E" android:pathData="M0,64h204v6h-204z" />
    <path android:fillColor="#0FDE41" android:pathData="M0,64h126v6h-126z" />
    <path android:fillColor="#1A1B2E" android:pathData="M204,0h96v70h-96z" />
    <path android:fillColor="#FFFFFF" android:pathData="M204,24h96v22h-96z" />
</vector>
`;

// Widget picker preview image for the forecast widgets: title, headline
// value, and a sparkline bar chart - representative of ForecastWidget.kt's
// actual Header/chart/Footer layout.
const forecastBar = (x: number, h: number, w = 16) =>
  `<path android:fillColor="#0FDE41" android:pathData="M${x},${110 - h}h${w}v${h}h-${w}z" />`;
const forecastPreviewImageVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="300dp" android:height="140dp"
    android:viewportWidth="300" android:viewportHeight="140">
    <path android:fillColor="#1B1B1B" android:pathData="M0,0h300v140h-300z" />
    <path android:fillColor="#0FDE41" android:pathData="M14,18h60v14h-60z" />
    <path android:fillColor="#FFFFFF" android:pathData="M226,14h60v16h-60z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M254,32h32v8h-32z" />
    ${[
      [14, 20],
      [35, 28],
      [56, 40],
      [77, 52],
      [98, 62],
      [119, 68],
      [140, 60],
      [161, 46],
      [182, 34],
      [203, 24],
      [224, 16],
      [245, 12],
      [266, 10],
    ]
      .map(([x, h]) => forecastBar(x, h))
      .join("\n    ")}
    <path android:fillColor="#B3FFFFFF" android:pathData="M14,122h100v10h-100z" />
    <path android:fillColor="#FFFFFF" android:pathData="M186,122h100v10h-100z" />
</vector>
`;

// Static preview layout for the widget picker (Glance content only renders once placed).
// 4x1: info area with the progress strip, three docked mode buttons (Smart selected).
const previewButton = (label: string, selected: boolean) =>
  `<TextView android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1"
        android:background="@color/widget_preview_${selected ? "dock_selected" : "dock"}" android:gravity="center"
        android:text="@string/${label}" android:textColor="@color/widget_preview_${selected ? "dock_selected_text" : "dock_text"}" android:textSize="12sp"${selected ? ' android:textStyle="bold"' : ""} />`;
const previewSeparator = `<ImageView android:layout_width="match_parent" android:layout_height="1dp" android:background="@color/widget_preview_card" />`;

// Light/dark palettes for the static picker preview, mirroring Theme.kt.
const previewColors = (c: Record<string, string>) =>
  `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${Object.entries(c)
    .map(([k, v]) => `    <color name="widget_preview_${k}">${v}</color>`)
    .join("\n")}\n</resources>\n`;
const previewColorsLight = previewColors({
  card: "#FFFFFF",
  text: "#1C1C1E",
  text_secondary: "#991C1C1E",
  status: "#0BA631",
  track: "#ECEEF0",
  dock: "#F0F1F3",
  dock_text: "#7C7D8A",
  dock_selected: "#000000",
  dock_selected_text: "#FFFFFF",
});
const previewColorsDark = previewColors({
  card: "#1C1C1E",
  text: "#FFFFFF",
  text_secondary: "#B3FFFFFF",
  status: "#0FDE41",
  track: "#38383A",
  dock: "#1A1B2E",
  dock_text: "#9A9BAB",
  dock_selected: "#FFFFFF",
  dock_selected_text: "#000000",
});

const loadpointPreviewXml = `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal"
    android:background="@drawable/widget_preview_card"
    android:clipToOutline="true">
  <FrameLayout android:layout_width="0dp" android:layout_weight="1" android:layout_height="match_parent">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent"
        android:orientation="horizontal" android:gravity="center_vertical"
        android:paddingStart="12dp" android:paddingEnd="12dp" android:paddingTop="6dp" android:paddingBottom="12dp">
      <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content"
          android:orientation="horizontal" android:gravity="bottom">
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="62" android:textColor="@color/widget_preview_text" android:textSize="36sp" android:textStyle="bold" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:paddingBottom="6dp"
            android:text=" %" android:textColor="@color/widget_preview_text_secondary" android:textSize="14sp" android:textStyle="bold" />
      </LinearLayout>
      <LinearLayout android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:layout_marginStart="14dp"
          android:paddingEnd="18dp" android:orientation="vertical">
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:maxLines="1" android:ellipsize="end"
            android:text="Garage" android:textColor="@color/widget_preview_text" android:textSize="14sp" android:textStyle="bold" />
        <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:orientation="horizontal" android:gravity="center_vertical" android:paddingTop="2dp">
          <ImageView android:layout_width="7dp" android:layout_height="7dp" android:background="@drawable/widget_preview_dot" />
          <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:paddingStart="5dp" android:maxLines="1"
              android:text="@string/widget_lpstatus_charging" android:textColor="@color/widget_preview_status" android:textSize="12sp" />
        </LinearLayout>
      </LinearLayout>
    </LinearLayout>
    <ImageView android:layout_width="15dp" android:layout_height="15dp" android:layout_gravity="top|end"
        android:layout_marginTop="8dp" android:layout_marginEnd="10dp"
        android:src="@drawable/ic_reload" android:tint="@color/widget_preview_text_secondary" />
    <LinearLayout android:layout_width="match_parent" android:layout_height="6dp" android:layout_gravity="bottom"
        android:orientation="horizontal" android:background="@color/widget_preview_track">
      <ImageView android:layout_width="0dp" android:layout_weight="62" android:layout_height="match_parent" android:background="#0FDE41" />
      <ImageView android:layout_width="0dp" android:layout_weight="38" android:layout_height="match_parent" />
    </LinearLayout>
  </FrameLayout>
  <LinearLayout android:layout_width="96dp" android:layout_height="match_parent" android:orientation="vertical" android:background="@color/widget_preview_dock">
    ${previewButton("widget_mode_off", false)}
    ${previewSeparator}
    ${previewButton("widget_mode_smart", true)}
    ${previewSeparator}
    ${previewButton("widget_mode_now", false)}
  </LinearLayout>
</LinearLayout>
`;

// Mirrors ForecastWidget.kt's DataBody: header row (title / value+unit / "now"),
// chart, footer row (two stat pieces) - same rounded card as the Loadpoint preview.
const forecastPreviewBar = (h: number) =>
  `<View android:layout_width="0dp" android:layout_weight="1" android:layout_height="${h}dp"
        android:layout_marginHorizontal="1dp" android:background="@color/widget_preview_status" />`;

const forecastPreviewXml = `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@drawable/widget_preview_card"
    android:clipToOutline="true"
    android:padding="12dp">
  <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content"
      android:orientation="horizontal" android:gravity="bottom">
    <TextView android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"
        android:text="@string/widget_type_solar" android:textColor="@color/widget_preview_status" android:textSize="15sp" android:textStyle="bold" />
    <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content" android:orientation="vertical" android:gravity="end">
      <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content" android:orientation="horizontal">
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="3.2" android:textColor="@color/widget_preview_status" android:textSize="15sp" android:textStyle="bold" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text=" kW" android:textColor="@color/widget_preview_status" android:textSize="10sp" android:textStyle="bold" />
      </LinearLayout>
      <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
          android:text="@string/widget_now" android:textColor="@color/widget_preview_text_secondary" android:textSize="9sp" />
    </LinearLayout>
  </LinearLayout>
  <View android:layout_width="match_parent" android:layout_height="4dp" />
  <LinearLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1"
      android:orientation="horizontal" android:gravity="bottom">
    ${[6, 10, 16, 24, 34, 40, 44, 38, 30, 20, 12, 6].map(forecastPreviewBar).join("\n    ")}
  </LinearLayout>
  <View android:layout_width="match_parent" android:layout_height="5dp" />
  <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="horizontal">
    <LinearLayout android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:orientation="horizontal">
      <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
          android:text="24 kWh" android:textColor="@color/widget_preview_status" android:textSize="10sp" android:textStyle="bold" />
      <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginStart="3dp"
          android:text="@string/widget_solar_remaining" android:textColor="@color/widget_preview_text_secondary" android:textSize="10sp" />
    </LinearLayout>
    <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content" android:orientation="horizontal">
      <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
          android:text="31 kWh" android:textColor="@color/widget_preview_text" android:textSize="10sp" android:textStyle="bold" />
      <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginStart="3dp"
          android:text="@string/widget_solar_tomorrow" android:textColor="@color/widget_preview_text_secondary" android:textSize="10sp" />
    </LinearLayout>
  </LinearLayout>
</LinearLayout>
`;

const roundedShape = (
  color: string,
  radius: string,
) => `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="${color}" />
    <corners android:radius="${radius}" />
</shape>
`;

// key → locale → value
type Translations = Record<string, Record<string, string>>;

function loadTranslations(projectRoot: string): {
  translations: Translations;
  locales: string[];
} {
  const catalog = JSON.parse(
    fs.readFileSync(path.join(projectRoot, XCSTRINGS), "utf8"),
  ) as {
    sourceLanguage: string;
    strings: Record<
      string,
      { localizations: Record<string, { stringUnit: { value: string } }> }
    >;
  };
  const translations: Translations = {};
  for (const [key, entry] of Object.entries(catalog.strings)) {
    translations[key] = Object.fromEntries(
      Object.entries(entry.localizations).map(([locale, l]) => [
        locale,
        l.stringUnit.value,
      ]),
    );
  }

  const i18nDir = path.join(projectRoot, APP_I18N);
  const locales = fs
    .readdirSync(i18nDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => path.basename(f, ".json"))
    .sort();
  const en = JSON.parse(fs.readFileSync(path.join(i18nDir, "en.json"), "utf8"));
  const androidOnlyKeys = Object.keys(en.widget?.androidConfig ?? {}).map(
    (k) => `${ANDROID_ONLY_PREFIX}${k}`,
  );
  const lookup = (json: Record<string, unknown>, key: string) =>
    key
      .split(".")
      .reduce<unknown>(
        (o, k) => (o as Record<string, unknown> | undefined)?.[k],
        json,
      );
  for (const key of androidOnlyKeys) translations[key] = {};
  for (const locale of locales) {
    const json = JSON.parse(
      fs.readFileSync(path.join(i18nDir, `${locale}.json`), "utf8"),
    );
    for (const key of androidOnlyKeys) {
      const value = lookup(json, key) ?? lookup(en, key);
      if (typeof value === "string") translations[key][locale] = value;
    }
  }
  return { translations, locales };
}

// Escape XML entities plus what Android's resource parser treats specially.
function escapeAndroid(value: string): string {
  let s = value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"');
  if (/^[@?]/.test(s)) s = `\\${s}`;
  return s;
}

// "widget.mode.off" → <string name="widget_mode_off">; "nb-NO" → values-b+nb+NO
function writeStrings(
  resDir: string,
  translations: Translations,
  locales: string[],
  sourceLang = "en",
) {
  const keys = Object.keys(translations).sort();
  for (const locale of locales) {
    const dir = path.join(
      resDir,
      locale === sourceLang
        ? "values"
        : `values-b+${locale.split("-").join("+")}`,
    );
    fs.mkdirSync(dir, { recursive: true });
    const entries = keys
      .map((key) => {
        const value =
          translations[key][locale] ?? translations[key][sourceLang];
        return `    <string name="${key.replace(/\./g, "_")}">${escapeAndroid(value)}</string>`;
      })
      .join("\n");
    const file = path.join(dir, "strings.xml");
    if (fs.existsSync(file)) {
      // prebuild already wrote app_name etc. into values/strings.xml — merge
      const existing = fs.readFileSync(file, "utf8");
      fs.writeFileSync(
        file,
        existing.replace("</resources>", `${entries}\n</resources>`),
      );
    } else {
      fs.writeFileSync(
        file,
        `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${entries}\n</resources>\n`,
      );
    }
  }
}

const withWidgetFiles: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const main = path.join(
        config.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
      );
      const res = path.join(main, "res");

      const dest = path.join(
        main,
        "java",
        ...PACKAGE.split("."),
        WIDGET_SUBDIR,
      );
      fs.mkdirSync(dest, { recursive: true });
      const srcDir = path.join(projectRoot, KOTLIN_SRC);
      for (const f of fs.readdirSync(srcDir).filter((f) => f.endsWith(".kt"))) {
        fs.copyFileSync(path.join(srcDir, f), path.join(dest, f));
      }

      const files: Record<string, string> = {
        "xml/loadpoint_widget_info.xml": widgetInfoXml,
        "xml/forecast_widget_info.xml": forecastInfoXml,
        "layout/loadpoint_widget_preview.xml": loadpointPreviewXml,
        "layout/forecast_widget_preview.xml": forecastPreviewXml,
        "drawable/widget_preview_loadpoint.xml": loadpointPreviewImageVector,
        "drawable/widget_preview_forecast.xml": forecastPreviewImageVector,
        "drawable/ic_reload.xml": reloadIconVector,
        "drawable/widget_preview_dot.xml": roundedShape(
          "@color/widget_preview_status",
          "4dp",
        ),
        "drawable/widget_preview_card.xml": roundedShape(
          "@color/widget_preview_card",
          "20dp",
        ),
        "values/colors_widget_preview.xml": previewColorsLight,
        "values-night/colors_widget_preview.xml": previewColorsDark,
      };
      for (const [rel, content] of Object.entries(files)) {
        const target = path.join(res, rel);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, content);
      }

      const { translations, locales } = loadTranslations(projectRoot);
      writeStrings(res, translations, locales);

      return config;
    },
  ]);

const withAndroidWidget: ConfigPlugin = (config) => {
  config = withComposeClasspath(config);
  config = withGlanceGradle(config);
  config = withWidgetManifest(config);
  config = withWidgetFiles(config);
  return config;
};

export default withAndroidWidget;
