import Foundation

/// Looks up a key in the autogenerated Localizable.xcstrings (device language).
/// Keys + translations are produced by `npm run widget:strings`.
enum L {
  static func t(_ key: String) -> String {
    Bundle.main.localizedString(forKey: key, value: key, table: nil)
  }
}
