/**
 * Generates targets/widget/Localizable.xcstrings (a String Catalog, for the iOS
 * widget extension) and Android string resources under
 * targets/android-widget/res/values(-b+<locale>)/strings.xml (for the Glance
 * widgets + config Activities) by compiling strings from TWO
 * community-translated sources:
 *
 *   - ../evcc/i18n  — the evcc daemon's translations (forecast type labels etc.)
 *   - ./i18n        — this app's translations (widget-only strings)
 *
 * Both are maintained on Weblate. Both outputs are fully autogenerated and
 * committed (CI builds the widgets without ../evcc present). Re-run after
 * wording changes:  npm run widget:strings
 *
 * Requires the evcc repo checked out next to this one (../evcc).
 */
import fs from "fs";
import path from "path";

const APP_I18N = "./i18n";
const EVCC_I18N = "../evcc/i18n";
const OUT = "./targets/widget/Localizable.xcstrings";
const ANDROID_RES_OUT = "./targets/android-widget/res";
const SOURCE_LANG = "en";

// iOS string key  →  { repo, dotted source key }
const KEYS: Record<string, { repo: "evcc" | "app"; key: string }> = {
  // type labels — reuse the evcc daemon translations (all locales)
  "widget.type.solar": { repo: "evcc", key: "forecast.type.solar" },
  "widget.type.co2": { repo: "evcc", key: "forecast.type.co2" },
  "widget.solar.remaining": { repo: "evcc", key: "forecast.solar.remaining" },
  "widget.solar.tomorrow": { repo: "evcc", key: "forecast.solar.tomorrow" },
  // loadpoint charge modes + statuses — reuse evcc daemon translations
  "widget.mode.off": { repo: "evcc", key: "main.mode.off" },
  "widget.mode.smart": { repo: "evcc", key: "main.mode.smart" },
  "widget.mode.now": { repo: "evcc", key: "main.mode.now" },
  "widget.mode.on": { repo: "evcc", key: "main.mode.on" },
  "widget.mode.normal": { repo: "evcc", key: "main.mode.normal" },
  "widget.mode.boost": { repo: "evcc", key: "main.mode.boost" },
  "widget.lpstatus.disconnected": { repo: "evcc", key: "main.vehicleStatus.disconnected" },
  "widget.lpstatus.connected": { repo: "evcc", key: "main.vehicleStatus.connected" },
  "widget.lpstatus.waitForVehicle": { repo: "evcc", key: "main.vehicleStatus.waitForVehicle" },
  "widget.lpstatus.finished": { repo: "evcc", key: "main.vehicleStatus.finished" },
  "widget.lpstatus.charging": { repo: "evcc", key: "main.vehicleStatus.charging" },
  "widget.lpheat.charging": { repo: "evcc", key: "main.heatingStatus.charging" },
  "widget.lpheat.connected": { repo: "evcc", key: "main.heatingStatus.connected" },
  "widget.lpheat.waitForVehicle": { repo: "evcc", key: "main.heatingStatus.waitForVehicle" },
  // everything else is widget-specific → this app's i18n
  "widget.type.price": { repo: "app", key: "widget.type.price" },
  "widget.type.feedin": { repo: "app", key: "widget.type.feedin" },
  "widget.now": { repo: "app", key: "widget.now" },
  "widget.noData.title": { repo: "app", key: "widget.noData.title" },
  "widget.noData.body": { repo: "app", key: "widget.noData.body" },
  "widget.unreachable.title": { repo: "app", key: "widget.unreachable.title" },
  "widget.unreachable.body": { repo: "app", key: "widget.unreachable.body" },
  "widget.setup.title": { repo: "app", key: "widget.setup.title" },
  "widget.setup.body": { repo: "app", key: "widget.setup.body" },
  "widget.config.title": { repo: "app", key: "widget.config.title" },
  "widget.config.desc": { repo: "app", key: "widget.config.desc" },
  "widget.config.server": { repo: "app", key: "widget.config.server" },
  "widget.config.loadpoint": { repo: "app", key: "widget.config.loadpoint" },
  // Android-only: the config Activities' picker/preview flow has no iOS equivalent
  // (App Intents don't render a live widget preview during configuration)
  "widget.androidConfig.chooseServer": { repo: "app", key: "widget.androidConfig.chooseServer" },
  "widget.androidConfig.chooseLoadpoint": { repo: "app", key: "widget.androidConfig.chooseLoadpoint" },
  "widget.androidConfig.noServers": { repo: "app", key: "widget.androidConfig.noServers" },
  "widget.androidConfig.noLoadpoints": { repo: "app", key: "widget.androidConfig.noLoadpoints" },
  "widget.androidConfig.loading": { repo: "app", key: "widget.androidConfig.loading" },
  "widget.androidConfig.loadingPreview": { repo: "app", key: "widget.androidConfig.loadingPreview" },
  "widget.androidConfig.previewError": { repo: "app", key: "widget.androidConfig.previewError" },
  "widget.androidConfig.useThisLoadpoint": { repo: "app", key: "widget.androidConfig.useThisLoadpoint" },
  "widget.androidConfig.useThis": { repo: "app", key: "widget.androidConfig.useThis" },
  "widget.androidConfig.adjustQuestion": { repo: "app", key: "widget.androidConfig.adjustQuestion" },
  "widget.androidConfig.yesRecommended": { repo: "app", key: "widget.androidConfig.yesRecommended" },
  "widget.androidConfig.no": { repo: "app", key: "widget.androidConfig.no" },
  "widget.loadpoint.name": { repo: "app", key: "widget.loadpoint.name" },
  "widget.loadpoint.description": { repo: "app", key: "widget.loadpoint.description" },
  "widget.name.solar": { repo: "app", key: "widget.name.solar" },
  "widget.name.price": { repo: "app", key: "widget.name.price" },
  "widget.name.co2": { repo: "app", key: "widget.name.co2" },
  "widget.name.feedin": { repo: "app", key: "widget.name.feedin" },
  "widget.description.solar": { repo: "app", key: "widget.description.solar" },
  "widget.description.price": { repo: "app", key: "widget.description.price" },
  "widget.description.co2": { repo: "app", key: "widget.description.co2" },
  "widget.description.feedin": { repo: "app", key: "widget.description.feedin" },
};

// Labels for legacy servers (pre smart-mode redesign). evcc removed
// main.mode.pv/minpv from its i18n, so the last Weblate state is frozen here.
// Locales missing from a map fall back to en.
const FROZEN: Record<string, Record<string, string>> = {
  "widget.mode.pv": {
    en: "Solar",
    cs: "Solár",
    da: "Sol",
    de: "PV",
    el: "Φ/Β",
    fi: "PV",
    fr: "Solaire",
    hr: "Solarno",
    hu: "Szolár",
    it: "Solare",
    ja: "太陽光",
    lb: "PV",
    lt: "Saulė",
    nl: "PV",
    pl: "Słońce",
    sk: "Solár",
    sl: "Sonce",
    sv: "Sol",
    ta: "ஞாயிறு",
    tr: "GES",
    uk: "Сонячна",
    "zh-Hans": "太阳能",
  },
  "widget.mode.minpv": {
    en: "Min+Solar",
    da: "Min+Sol",
    de: "Min+PV",
    el: "Ελαχ+Φ/Β",
    fi: "Min+PV",
    fr: "Min+Solaire",
    hr: "Min+Solarno",
    hu: "Min+Szolár",
    it: "Min+Solare",
    ja: "Min+太陽光",
    lb: "Min+PV",
    lt: "Min+Saulė",
    nl: "Min+PV",
    pl: "Min+Słońce",
    sk: "Min+Solár",
    sl: "Min+Sonce",
    sv: "Min+Sol",
    ta: "குறை+ஞாயிறு",
    tr: "Asg.+GES",
    uk: "Мін+Сонце",
    "zh-Hans": "最少+太阳能",
  },
};

if (!fs.existsSync(EVCC_I18N)) {
  console.error(
    `[widget:strings] ${EVCC_I18N} not found. Check out the evcc repo next to this one.`,
  );
  process.exit(1);
}

const cache: Record<string, Record<string, unknown> | null> = {};
function load(repo: "evcc" | "app", locale: string): Record<string, unknown> | null {
  const file = path.join(repo === "evcc" ? EVCC_I18N : APP_I18N, `${locale}.json`);
  if (!(file in cache)) {
    cache[file] = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : null;
  }
  return cache[file];
}

function dig(obj: unknown, dotted: string): string | undefined {
  let cur: unknown = obj;
  for (const part of dotted.split(".")) {
    if (cur && typeof cur === "object" && part in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[part];
    } else {
      return undefined;
    }
  }
  return typeof cur === "string" ? cur : undefined;
}

// look up a key for a locale, falling back to the language part (e.g. nb-NO → nb)
function lookup(repo: "evcc" | "app", key: string, locale: string): string | undefined {
  return (
    dig(load(repo, locale), key) ??
    (locale.includes("-") ? dig(load(repo, locale.split("-")[0]), key) : undefined)
  );
}

// ship the widget in the locales this app already supports
const locales = fs
  .readdirSync(APP_I18N)
  .filter((f) => f.endsWith(".json"))
  .map((f) => path.basename(f, ".json"))
  .sort();

// key → locale → resolved value (source-language fallback already applied)
const translations: Record<string, Record<string, string>> = {};
const missing: string[] = [];

for (const [key, src] of Object.entries(KEYS)) {
  const en = lookup(src.repo, src.key, SOURCE_LANG);
  if (en === undefined) {
    missing.push(`${key} (${src.repo}:${src.key})`);
    continue;
  }
  const byLocale: Record<string, string> = {};
  for (const locale of locales) {
    byLocale[locale] = lookup(src.repo, src.key, locale) ?? en;
  }
  translations[key] = byLocale;
}

for (const [key, frozen] of Object.entries(FROZEN)) {
  const byLocale: Record<string, string> = {};
  for (const locale of locales) {
    byLocale[locale] = frozen[locale] ?? frozen[locale.split("-")[0]] ?? frozen[SOURCE_LANG];
  }
  translations[key] = byLocale;
}

if (missing.length) {
  console.error(`[widget:strings] missing source (en) strings:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

// --- iOS: targets/widget/Localizable.xcstrings ---

const strings: Record<string, unknown> = {};
for (const [key, byLocale] of Object.entries(translations)) {
  const localizations: Record<string, unknown> = {};
  for (const [locale, value] of Object.entries(byLocale)) {
    localizations[locale] = { stringUnit: { state: "translated", value } };
  }
  strings[key] = { extractionState: "manual", localizations };
}
const catalog = { sourceLanguage: SOURCE_LANG, strings, version: "1.0" };
fs.writeFileSync(OUT, JSON.stringify(catalog, null, 2) + "\n");
console.log(
  `[widget:strings] wrote ${OUT} — ${Object.keys(strings).length} keys × ${locales.length} locales`,
);

// --- Android: targets/android-widget/res/values*/strings.xml ---

// "widget.mode.off" -> "widget_mode_off" (Android resource names are identifiers)
function androidName(key: string): string {
  return key.replace(/\./g, "_");
}

// Android string resources: escape XML entities plus the characters Android's
// own resource parser treats specially (apostrophe, quote, @/? at the start).
function escapeAndroid(value: string): string {
  let s = value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/'/g, "\\'")
    .replace(/"/g, "\\\"");
  if (/^[@?]/.test(s)) s = `\\${s}`;
  return s;
}

// BCP-47 resource qualifier: "de" -> "b+de", "nb-NO" -> "b+nb+NO" (the modern
// `b+` syntax handles arbitrary language/region/script tags without needing to
// map each one to the older `xx-rYY` qualifier form).
function androidLocaleDir(locale: string): string {
  return `values-b+${locale.split("-").join("+")}`;
}

function writeAndroidStrings(dir: string, keys: [string, string][]) {
  fs.mkdirSync(dir, { recursive: true });
  const body = keys
    .map(([name, value]) => `    <string name="${name}">${escapeAndroid(value)}</string>`)
    .join("\n");
  const xml = `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${body}\n</resources>\n`;
  fs.writeFileSync(path.join(dir, "strings.xml"), xml);
}

// clear previously generated locale dirs so removed locales don't linger
if (fs.existsSync(ANDROID_RES_OUT)) {
  for (const entry of fs.readdirSync(ANDROID_RES_OUT)) {
    if (entry === "values" || entry.startsWith("values-b+")) {
      fs.rmSync(path.join(ANDROID_RES_OUT, entry), { recursive: true, force: true });
    }
  }
}

const keyNames = Object.keys(translations).sort();
writeAndroidStrings(
  path.join(ANDROID_RES_OUT, "values"),
  keyNames.map((key) => [androidName(key), translations[key][SOURCE_LANG]]),
);
for (const locale of locales) {
  if (locale === SOURCE_LANG) continue;
  writeAndroidStrings(
    path.join(ANDROID_RES_OUT, androidLocaleDir(locale)),
    keyNames.map((key) => [androidName(key), translations[key][locale]]),
  );
}
console.log(
  `[widget:strings] wrote ${ANDROID_RES_OUT}/values*/strings.xml — ${keyNames.length} keys × ${locales.length} locales`,
);
