/**
 * Generates targets/widget/Localizable.xcstrings (a String Catalog) for the iOS
 * widget extension by compiling strings from TWO community-translated sources:
 *
 *   - ../evcc/i18n  — the evcc daemon's translations (forecast type labels etc.)
 *   - ./i18n        — this app's translations (widget-only strings)
 *
 * Both are maintained on Weblate. The .xcstrings is fully autogenerated and
 * committed (CI builds the widget without ../evcc present). Re-run after wording
 * changes:  npm run widget:strings
 *
 * Requires the evcc repo checked out next to this one (../evcc).
 */
import fs from "fs";
import path from "path";

const APP_I18N = "./i18n";
const EVCC_I18N = "../evcc/i18n";
const OUT = "./targets/widget/Localizable.xcstrings";
const SOURCE_LANG = "en";

// iOS string key  →  { repo, dotted source key }
const KEYS: Record<string, { repo: "evcc" | "app"; key: string }> = {
  // type labels — reuse the evcc daemon translations (all locales)
  "widget.type.solar": { repo: "evcc", key: "forecast.type.solar" },
  "widget.type.co2": { repo: "evcc", key: "forecast.type.co2" },
  "widget.solar.remaining": { repo: "evcc", key: "forecast.solar.remaining" },
  "widget.solar.tomorrow": { repo: "evcc", key: "forecast.solar.tomorrow" },
  // loadpoint charge modes + statuses — reuse evcc daemon translations
  "widget.mode.off": { repo: "evcc", key: "main.mode.off" },
  "widget.mode.pv": { repo: "evcc", key: "main.mode.pv" },
  "widget.mode.minpv": { repo: "evcc", key: "main.mode.minpv" },
  "widget.mode.now": { repo: "evcc", key: "main.mode.now" },
  "widget.lpstatus.disconnected": { repo: "evcc", key: "main.vehicleStatus.disconnected" },
  "widget.lpstatus.connected": { repo: "evcc", key: "main.vehicleStatus.connected" },
  "widget.lpstatus.waitForVehicle": { repo: "evcc", key: "main.vehicleStatus.waitForVehicle" },
  "widget.lpstatus.finished": { repo: "evcc", key: "main.vehicleStatus.finished" },
  "widget.lpstatus.charging": { repo: "evcc", key: "main.vehicleStatus.charging" },
  "widget.lpheat.charging": { repo: "evcc", key: "main.heatingStatus.charging" },
  "widget.lpheat.connected": { repo: "evcc", key: "main.heatingStatus.connected" },
  "widget.lpheat.waitForVehicle": { repo: "evcc", key: "main.heatingStatus.waitForVehicle" },
  // everything else is widget-specific → this app's i18n
  "widget.solar.adjust": { repo: "app", key: "widget.solar.adjust" },
  "widget.type.price": { repo: "app", key: "widget.type.price" },
  "widget.type.feedin": { repo: "app", key: "widget.type.feedin" },
  "widget.now": { repo: "app", key: "widget.now" },
  "widget.noData.title": { repo: "app", key: "widget.noData.title" },
  "widget.noData.body": { repo: "app", key: "widget.noData.body" },
  "widget.unreachable.title": { repo: "app", key: "widget.unreachable.title" },
  "widget.unreachable.body": { repo: "app", key: "widget.unreachable.body" },
  "widget.setup.title": { repo: "app", key: "widget.setup.title" },
  "widget.setup.body": { repo: "app", key: "widget.setup.body" },
  "widget.config.title": { repo: "app", key: "widget.config.title" },
  "widget.config.desc": { repo: "app", key: "widget.config.desc" },
  "widget.config.server": { repo: "app", key: "widget.config.server" },
  "widget.config.loadpoint": { repo: "app", key: "widget.config.loadpoint" },
  "widget.loadpoint.name": { repo: "app", key: "widget.loadpoint.name" },
  "widget.loadpoint.description": { repo: "app", key: "widget.loadpoint.description" },
  "widget.name.solar": { repo: "app", key: "widget.name.solar" },
  "widget.name.price": { repo: "app", key: "widget.name.price" },
  "widget.name.co2": { repo: "app", key: "widget.name.co2" },
  "widget.name.feedin": { repo: "app", key: "widget.name.feedin" },
  "widget.description.solar": { repo: "app", key: "widget.description.solar" },
  "widget.description.price": { repo: "app", key: "widget.description.price" },
  "widget.description.co2": { repo: "app", key: "widget.description.co2" },
  "widget.description.feedin": { repo: "app", key: "widget.description.feedin" },
};

if (!fs.existsSync(EVCC_I18N)) {
  console.error(
    `[widget:strings] ${EVCC_I18N} not found. Check out the evcc repo next to this one.`,
  );
  process.exit(1);
}

const cache: Record<string, Record<string, unknown> | null> = {};
function load(repo: "evcc" | "app", locale: string): Record<string, unknown> | null {
  const file = path.join(repo === "evcc" ? EVCC_I18N : APP_I18N, `${locale}.json`);
  if (!(file in cache)) {
    cache[file] = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : null;
  }
  return cache[file];
}

function dig(obj: unknown, dotted: string): string | undefined {
  let cur: unknown = obj;
  for (const part of dotted.split(".")) {
    if (cur && typeof cur === "object" && part in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[part];
    } else {
      return undefined;
    }
  }
  return typeof cur === "string" ? cur : undefined;
}

// look up a key for a locale, falling back to the language part (e.g. nb-NO → nb)
function lookup(repo: "evcc" | "app", key: string, locale: string): string | undefined {
  return (
    dig(load(repo, locale), key) ??
    (locale.includes("-") ? dig(load(repo, locale.split("-")[0]), key) : undefined)
  );
}

// ship the widget in the locales this app already supports
const locales = fs
  .readdirSync(APP_I18N)
  .filter((f) => f.endsWith(".json"))
  .map((f) => path.basename(f, ".json"))
  .sort();

const strings: Record<string, unknown> = {};
const missing: string[] = [];

for (const [iosKey, src] of Object.entries(KEYS)) {
  const en = lookup(src.repo, src.key, SOURCE_LANG);
  if (en === undefined) {
    missing.push(`${iosKey} (${src.repo}:${src.key})`);
    continue;
  }
  const localizations: Record<string, unknown> = {};
  for (const locale of locales) {
    const value = lookup(src.repo, src.key, locale) ?? en;
    localizations[locale] = { stringUnit: { state: "translated", value } };
  }
  strings[iosKey] = { extractionState: "manual", localizations };
}

if (missing.length) {
  console.error(`[widget:strings] missing source (en) strings:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const catalog = { sourceLanguage: SOURCE_LANG, strings, version: "1.0" };
fs.writeFileSync(OUT, JSON.stringify(catalog, null, 2) + "\n");
console.log(
  `[widget:strings] wrote ${OUT} — ${Object.keys(strings).length} keys × ${locales.length} locales`,
);
